--Scaffold-DbContext "Server=localhost\SQLEXPRESS;Database=B1RADIO;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Force

-- DDL section --

CREATE DATABASE B1RADIO;
GO

USE B1RADIO;
GO

CREATE TABLE GENRE (
    ID int NOT NULL IDENTITY,
    NAME nvarchar(150) NOT NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY (ID),
	CONSTRAINT UQ_GENRE_NAME UNIQUE(NAME)
);
GO

CREATE TABLE SINGER (
    ID int NOT NULL IDENTITY,
    NAME nvarchar(150) NOT NULL,
    CONSTRAINT PK_SINGER PRIMARY KEY (ID),
	CONSTRAINT UQ_SINGER_NAME UNIQUE(NAME)
);
GO

CREATE TABLE SOUNDTRACK (
    ID int NOT NULL IDENTITY,
    GENRE_ID int NOT NULL,
	SINGER_ID int NOT NULL,
    TITLE nvarchar(150) NOT NULL,
    SERVER_FILENAME nvarchar(150) NOT NULL,
	CLIENT_FILENAME nvarchar(max) NOT NULL,
    CONSTRAINT PK_SOUNDTRACK PRIMARY KEY (ID),
    CONSTRAINT FK_SOUNDTRACK_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID),
	CONSTRAINT FK_SOUNDTRACK_SINGER_ID FOREIGN KEY (SINGER_ID) REFERENCES SINGER (ID),
	CONSTRAINT UQ_SOUNDTRACK_SINGERTITLE UNIQUE(SINGER_ID, TITLE),
	CONSTRAINT UQ_SOUNDTRACK_SRVFILENAME UNIQUE(SERVER_FILENAME)
);
GO

-- DML section --

INSERT INTO GENRE (NAME) VALUES ('Pop');
INSERT INTO GENRE (NAME) VALUES ('Rock');
INSERT INTO GENRE (NAME) VALUES ('Dance');
INSERT INTO GENRE (NAME) VALUES ('Latin');
GO
